# Setup
title: Blog
tagline: Hacking and Open-source Intelligence Tools I Found
url: https://n-8.co.za
paginate: 1
baseurl: ""
permalink: :title/

kramdown:
    footnote_backlink: "&#10548;"

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-target-blank

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Specify the author for blog posts
author:
  name: Blue Diablos
  url: ""
  email: ""

# Custom vars
version: 1.3.0
github:
  repo: https://github.com/essentialenemy/noir
